# Docker outside Docker.
jenkins:
  build: .
  container_name: jenkins_dood
  privileged: true
  restart: always
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes:
    # mount docker binary and socket from host
    - /home/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
